name: Unzip all gallery zip files and commit

on:
  push:
    paths:
      - 'gallery/**/*.zip'

jobs:
  unzip_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip all zip files in gallery directories
        run: |
          shopt -s globstar nullglob
          for f in gallery/**/*.zip; do
            folder="${f%.*}_unzipped"
            mkdir -p "$folder"
            unzip -o "$f" -d "$folder"
          done

      - name: Set up git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit unzipped files
        run: |
          git add gallery/**/*_unzipped
          git commit -m "Auto-unzip all zip files in gallery"
          git push
        continue-on-error: true
